"""empty message

Revision ID: 361be2e2f7d8
Revises: 
Create Date: 2020-07-02 17:40:56.077471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361be2e2f7d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    # ### end Alembic commands ###
