"""empty message

Revision ID: 96771ef6691a
Revises: 
Create Date: 2020-07-15 23:05:16.205395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96771ef6691a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('profile_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('person', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
